### ISSUE TITLE
When opening a badly formatted FASTA file, ReadParser error is unclear.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1119]
When running load-into-counting on a badly formatted FASTA file, I get:

```
scripts/load-into-counting.py", line 111, in main
    rparser = khmer.ReadParser(filename)
ValueError: Could not open reads.fa for reading.
```

This error message seems to be coming from the zlib library (!?)

**Comment by ctb** [comment]
We should get:

   Could not parse reads.fa file

**Comment by mr-c** [comment]
@ctb Is this still a problem?

**Comment by ctb** [comment]
Yeppers.

```
% echo foo > test.fa
% scripts/load-into-counting.py xxx test.fa

|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 2.0-rc1+377.g9671c9d
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. http://dx.doi.org/10.6084/m9.figshare.979190
||   * Q Zhang et al., http://dx.doi.org/10.1371/journal.pone.0101271
||   * A. Döring et al. http://dx.doi.org:80/10.1186/1471-2105-9-11
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.


PARAMETERS:
 - kmer size =    32            (-k)
 - n tables =     4             (-N)
 - max tablesize = 1e+06        (-x)

Estimated memory usage is 4e+06 bytes (n_tables x max_tablesize)
--------

** WARNING: tablesize is default!
** You probably want to increase this with -M/--max-memory-usage!
** Please read the docs!

Saving k-mer counting table to xxx
Loading kmers from sequences in ['test.fa']
making countgraph
Traceback (most recent call last):
  File "scripts/load-into-counting.py", line 183, in <module>
    main()
  File "scripts/load-into-counting.py", line 110, in main
    rparser = khmer.ReadParser(filename)
OSError: Could not open test.fa for reading.
```
