### ISSUE TITLE
Warning message about improperly interleaved pairs

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1140]
I'm looking at some rice data (SRA accession ERR612477), and I get an `improperly interleaved pairs` message for the first read pair when running `normalize-by-median.py`. I don't see any formatting issues with the read IDs (see first two pairs below). Any idea what may be causing this error message?

By the way, I pip installed khmer 1.4.1 on a Fedora machine.

```
@ERR612477.1 FCD0LYEACXX:1:1101:1182:2032/1
GAGACAGTCTTGCAATCCTTCAAACCCAAATCCACACAAACACATACTCCGAAATCGTCACCAAATTTTCCCTCCGAATCACC
+
FHHHHHJIJJJGJJJJJJJJJJIEIJJJIGIIJEGIJJJJIJJJJJJJJJJHJHHHHFFFFEEBDEDDDEDDDDDBBDDDDD9
@ERR612477.1 FCD0LYEACXX:1:1101:1182:2032/2
CACCCGCCGCCGGCGGCCAACACCACCGGCGCGGCCTCCACCCCGGACTGGTTCCGGCCTAGGGCGCCGCCCGACGCGGACCC
+
FHHGHHJJJJJJJIJGFDDDDDDDBDDBDDBDDDD6&8A3((0077550<<C@C>;5;7039C####################
@ERR612477.2 FCD0LYEACXX:1:1101:2154:2076/1
CGCCGGCGACCAACGGCGCGGCGGAGCGGCGGCCGAGAGAGGGGAGGGAAGGGGGAAGCGAAAGAGGCGGTCCACGGCTCACC
+
FHHHHHJJJJJJJJJHHDDDDDDDDDDDDBDB@B@39072<@DD59BD6?@DDDD5;@@BBBD;?AB?>@59@CC?>9<>3(2
@ERR612477.2 FCD0LYEACXX:1:1101:2154:2076/2
CCCCTTATAGTATAATCCCTTTGTACTCCCTTGCATTTATTTTGCATCTGCGGGTGTGTCTTGTTGAGTACGGTGGTTGTACT
+
FHHHHHJJIJFIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJIJJJJJJJJJJ:E?DDEEECCEACC@ACDD<?B8??>AAD
```

**Comment by standage** [comment]
Hmm, I get this when running `split-paired-reads.py`.

```
Unrecognized format for read pair information: ERR612477.1 FCD0LYEACXX:1:1101:1182:2032/1
```

Is this format non-standard?

**Comment by kdmurray91** [comment]
`fastq-dump` somewhat mangles the header line. I use `--defline-seq='@$sn/$ri' --defline-qual '+'`, which fixes the issue. If you want the accession in there too, I'd do `--defline-seq='@$sn/$ri $ac'`.

**Comment by ctb** [comment]
@standage I believe @SherineAwad fixed this in #1088, which will be part of the 2.0 release - a quick test applying split-paired-reads.py to your data above suggests that it is indeed fixed. Let us know if you find that it is not so. @kdmurray91 does your comment still apply?

**Comment by standage** [comment]
@ctb @SherineAwad I get this when I `make test` on the latest master (OS X Yosemite).

```
======================================================================
FAIL: tests.test_read_parsers.test_read_pair_iterator_in_error_mode_xfail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/standage/Desktop/temp-env/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/standage/Desktop/khmer/tests/test_read_parsers.py", line 337, in test_read_pair_iterator_in_error_mode_xfail
    assert "Invalid read pair" in str(exc), str(exc)
AssertionError

----------------------------------------------------------------------
Ran 560 tests in 30.559s

FAILED (failures=1)
make: *** [test] Error 1
```

**Comment by SherineAwad** [comment]
Hi @ctb and @standage  

I tested the sample sequence, and it doesn't work. There is another bug I will handle. Thanks.

**Comment by SherineAwad** [comment]
@standage  @ctb 
Sorry, something was wrong with my virtual env. 
Now, checking the sample sequence  with interleave-reads, it works. Will go through errors thrown from other scripts you mentioned.

**Comment by ctb** [comment]
@standage @SherineAwad did we ever figure out what was happening? I think everything is working for me and @SherineAwad...

**Comment by standage** [comment]
@ctb @SherineAwad Still getting the same error on OS X Yosemite (multiple machines). Tests pass fine on one of our lab's Fedora VMs.

**Comment by standage** [comment]
@ctb @SherineAwad Actually, the script seems to be working fine both on Fedora and Mac OS X: but the test is still failing on OS X.

**Comment by kdmurray91** [comment]
@standage that test is known to be failing on OS X, see #1046.

**Comment by mr-c** [comment]
What's the status of this issue?

**Comment by kdmurray91** [comment]
This should be fixed by #1173, is that true @standage (your comment above suggests it is true)

**Comment by standage** [comment]
Weird. I'm now seeing the following errors on Ubuntu 16.04 (Python 2.7 and 3.5), but not on Mac.

```
=================================================================== FAILURES ===================================================================
___________________________________________________________ test_num_reads_truncated ___________________________________________________________

    def test_num_reads_truncated():
    
        n_reads = 0
        rparser = ReadParser(utils.get_test_data("truncated.fq"))
        try:
            for _ in rparser:
                n_reads += 1
        except ValueError as err:
>           assert "Sequence is empty" in str(err), str(err)
E           AssertionError: �P�
E           assert 'Sequence is empty' in '\xe0P\xa7\x02'
E            +  where '\xe0P\xa7\x02' = str(ValueError('\xe0P\xa7\x02',))

tests/test_read_parsers.py:117: AssertionError
_____________________________________________________________ test_read_truncated ______________________________________________________________

    def test_read_truncated():
    
        rparser = ReadParser(utils.get_test_data("truncated.fq"))
        try:
            for _ in rparser:
                pass
            assert 0, "No exception raised on a truncated file"
        except ValueError as err:
>           assert "Sequence is empty" in str(err), str(err)
E           AssertionError: Ј�
E           assert 'Sequence is empty' in '\xd0\x88\xcf\x03'
E            +  where '\xd0\x88\xcf\x03' = str(ValueError('\xd0\x88\xcf\x03',))

tests/test_read_parsers.py:305: AssertionError
_________________________________________________ test_read_pair_iterator_in_error_mode_xfail __________________________________________________

    @pytest.mark.linux
    def test_read_pair_iterator_in_error_mode_xfail():
    
        rparser = \
            ReadParser(utils.get_test_data("test-abund-read-impaired.fa"))
    
        failed = True
        try:
            for _ in rparser.iter_read_pairs():
                pass
            failed = False
        except ValueError as exc:
>           assert "Invalid read pair" in str(exc), str(exc)
E           AssertionError: 3
E           assert 'Invalid read pair' in '\x10\x013\x04'
E            +  where '\x10\x013\x04' = str(ValueError('\x10\x013\x04',))

tests/test_read_parsers.py:361: AssertionError
================================= 22 tests deselected by "-m 'not known_failing and not jenkins and not huge'" =================================
============================================= 3 failed, 655 passed, 22 deselected in 41.49 seconds =============================================
```

I'm still trying to wrap my mind around the error handling and passing between C++ and Python.

**Comment by mr-c** [comment]
@standage I see this sometimes on Debian 'sid' unstable, it seemed to be bugs in their Python compilation that I never tracked down. Seems that bug has made it into Ubuntu :-/

**Comment by ctb** [comment]
On Tue, May 17, 2016 at 07:46:43AM -0700, Michael R. Crusoe wrote:
> @standage I see this sometimes on Debian 'sid' unstable, it seemed to be bugs in their Python compilation that I never tracked down. Seems that bug has made it into Ubuntu :-/

Yep. I also see it on AWS VMs pretty regularly.

**Comment by ctb** [comment]
The original report should no longer be a problem :)
