### ISSUE TITLE
Normalize-by-median makes .keep files for stuff it skips

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1174]
```
WARNING: Input file empty is empty
making countgraph
SKIPPED empty file empty
output in empty.keep
Total number of unique k-mers: 0
fp rate estimated to be 0.000
(env)bocajnotnef@GCU-Caconym:~/git/khmer⟫ git status
On branch fix/spacechecks
Your branch is up-to-date with 'origin/fix/spacechecks'.
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        empty
        empty.keep

nothing added to commit but untracked files present (use "git add" to track)
(env)bocajnotnef@GCU-Caconym:~/git/khmer⟫ 
```

**Comment by bocajnotnef** [comment]
this is evidently intended behaviour.

I broke a test.

```
FAIL: tests.test_normalize_by_median.test_normalize_by_median_empty
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/bocajnotnef/git/env/local/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/home/bocajnotnef/git/khmer/tests/test_normalize_by_median.py", line 451, in test_normalize_by_median_empty
    assert os.path.exists(outfile), outfile
AssertionError: /tmp/khmertest_GT4eWk/test.fa.keep
```
