### ISSUE TITLE
Make Jenkins auto-retest on "could not check out" failure

### ISSUE THREAD

**Issue by bocajnotnef** [dib-lab/khmer#1246]
the "could not check out" failure happens annoyingly often and is resolved by asking jenkins to "retest this please"

Would be great if it kicked itself into a retest

```
Checking out Revision 7a5938596671e5a94ab324c1e60f1a03a20a669e (refs/remotes/origin/pr/1241/merge)
 > git config core.sparsecheckout # timeout=10
 > git checkout -f 7a5938596671e5a94ab324c1e60f1a03a20a669e
FATAL: Could not checkout 7a5938596671e5a94ab324c1e60f1a03a20a669e
hudson.plugins.git.GitException: Could not checkout 7a5938596671e5a94ab324c1e60f1a03a20a669e
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1867)
	at hudson.plugins.git.GitSCM.checkout(GitSCM.java:1060)
	at hudson.scm.SCM.checkout(SCM.java:484)
	at hudson.model.AbstractProject.checkout(AbstractProject.java:1270)
	at hudson.model.AbstractBuild$AbstractBuildExecution.defaultCheckout(AbstractBuild.java:609)
	at jenkins.scm.SCMCheckoutStrategy.checkout(SCMCheckoutStrategy.java:86)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:531)
	at hudson.model.Run.execute(Run.java:1741)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
Caused by: hudson.plugins.git.GitException: Command "git checkout -f 7a5938596671e5a94ab324c1e60f1a03a20a669e" returned status code 128:
stdout: 
stderr: fatal: reference is not a tree: 7a5938596671e5a94ab324c1e60f1a03a20a669e

	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:1600)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:61)
	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$8.execute(CliGitAPIImpl.java:1859)
	... 10 more
[WARNINGS] Skipping publisher since build result is FAILURE
Publish Cobertura Coverage Report is waiting for a checkpoint on khmer-pullrequest » linux #3067
Skipping Cobertura coverage report as build was not UNSTABLE or better ...
[htmlpublisher] Archiving HTML reports...
[htmlpublisher] Archiving at PROJECT level /var/lib/jenkins/workspace/khmer-pullrequest@3/label/linux/build/sphinx/html to /var/lib/jenkins/jobs/khmer-pullrequest/configurations/axis-label/linux/htmlreports/Sphinx_Docs
Recording test results
ERROR: Publisher hudson.tasks.junit.JUnitResultArchiver aborted due to exception
hudson.AbortException: No test report files were found. Configuration error?
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:116)
	at hudson.tasks.junit.JUnitParser$ParseResultCallable.invoke(JUnitParser.java:93)
	at hudson.FilePath.act(FilePath.java:989)
	at hudson.FilePath.act(FilePath.java:967)
	at hudson.tasks.junit.JUnitParser.parseResult(JUnitParser.java:90)
	at hudson.tasks.junit.JUnitResultArchiver.parse(JUnitResultArchiver.java:120)
	at hudson.tasks.junit.JUnitResultArchiver.perform(JUnitResultArchiver.java:137)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:74)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:721)
	at hudson.model.Build$BuildExecution.post2(Build.java:183)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:670)
	at hudson.model.Run.execute(Run.java:1766)
	at hudson.matrix.MatrixRun.run(MatrixRun.java:146)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:374)
[BFA] Scanning build for known causes...
[BFA] No failure causes found
[BFA] Done. 0s
Finished: FAILURE
```

**Comment by mr-c** [comment]
Agreed! Lets start by chasing this with upstream. I don't know if it has been properly reported to them or not.

**Comment by standage** [comment]
Was this pursued at all. If not I'm inclined to close, or punt at the very least.

**Comment by mr-c** [comment]
I didn't follow up, no. The Jenkins install and plugins are out of date on
ci.oxli.org last I checked.

**Comment by ctb** [comment]
sure, close w/wontfix
