### ISSUE TITLE
no streaming for load-into-counting.py?

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1265]
the command: 

```
interleave-reads.py R1.fq R2.fq \
| load-into-counting.py -t 20 -k 32 --min-tablesize 8e10 -
```

the error:
```
|| This is the script 'load-into-counting.py' in khmer.
|| You are running khmer version 1.1
|| You are also using screed version 0.7
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2014. doi: 10.6084/m9.figshare.979190
||   * Q Zhang et al., arXiv:1309.2975 [q-bio.GN]
||
|| Please see the CITATION file for details.


PARAMETERS:
 - kmer size =    32            (-k)
 - n tables =     4             (-N)
 - min tablesize = 8e+10        (-x)

Estimated memory usage is 3.2e+11 bytes (n_tables x min_tablesize)
--------
ERROR: Input file - does not exist; exiting

|| This is the script interleave-reads.py in khmer.
|| You are running khmer version 2.0-rc3+66.g94d679f
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.

Interleaving:
        R1.fq
        R2.fq
... 0 pairs
Traceback (most recent call last):
  File "/usr/local/bin/interleave-reads.py", line 4, in <module>
    __import__('pkg_resources').run_script('khmer==2.0rc3+66.g94d679f', 'interleave-reads.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/EGG-INFO/scripts/interleave-reads.py", line 123, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/EGG-INFO/scripts/interleave-reads.py", line 117, in main
    write_record_pair(read1, read2, outfp)
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/khmer/utils.py", line 202, in write_record_pair
    write_record(read2, fileobj)
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/khmer/utils.py", line 194, in write_record
    fileobj.write(recstr)
IOError: [Errno 32] Broken pipe
```

**Comment by ctb** [comment]
Try this with load-into-countgraph; this is an old version of khmer, and
you got messed up by the rename of the script.

See #1256 for an issue suggesting that this rename be undone.

--titus

**Comment by macmanes** [comment]
Gotcha:

This seems to work.
```
interleave-reads.py R1.fq R2.fq \
| load-into-countgraph.py --threads 20 --ksize 32 -M 8e10 count.kh -
```

More generally, how would end-user know this? Is there a guide somewhere that I am missing?

**Comment by mr-c** [comment]
@macmanes know about the rename or know about the support for streaming?

**Comment by ctb** [comment]
@macmanes there's a doc/whats-new-2.0 file that we'll link prominently upon release.

I'm going to close this in favor of #1256.
