### ISSUE TITLE
interleave-reads.py fails to run 

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#1273]
It throughs this exception

Traceback (most recent call last):
  File "/mnt/home/mansourt/env/bin/interleave-reads.py", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/mnt/home/mansourt/khmer/scripts/interleave-reads.py", line 26, in <module>
    import khmer
  File "/mnt/home/mansourt/khmer/khmer/__init__.py", line 13, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: cannot import name Countgraph

**Comment by mr-c** [comment]
If you've been following the latest development version I recommend deleting your virtualenv and making a new one.

**Comment by drtamermansour** [comment]
I upgraded to virtualenv 13.1.2 and also I had to use a more recent version of GNU on HPC (GNU 4.7.1 instead of the default GNU 4.4.5). Now it is working fine. Thank you

**Comment by mr-c** [comment]
I'm glad to hear that you got it resolved.
