### ISSUE TITLE
split-paired-reads.py breaks with broken interleaved?

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1276]
Hi people, 

I thought with `2.0-rc3+66.g94d679f` and `screed version 0.9` that all tools could take broken interleaved? Anyway, seems that `split-paired-reads.py` does not.. When processing files like this:

```
interleave-reads.py R1.fq R2.fq \
| normalize-by-median.py --max-memory-usage 2e10 -C 30 -o -  - \
| trim-low-abund.py -M 2e10 -o dp.2pass_take_two.fq --cutoff 2 -
```

Then 

```
split-paired-reads.py dp.2pass_take_two.fq
```

I fail with 

```
...
... 33410000
... 33420000
... 33430000
Unpaired reads found starting at HSQ-7001360:236:H3L3YBCXX:2:1101:1172:2135 2:N:0:ATCACGATCTCG; exiting
```

Indeed, the /1 pair is lost somewhere in the filtering process, but I thought that should be OK.

```
@HSQ-7001360:236:H3L3YBCXX:2:1101:1217:2131 1:N:0:ATCACGATCTCG
GNGGGTTTGCCCGGGGGATGTTCAAGTTTTGGATTGATCTCTACATAACTTGGATGGTATAAGGCATAGCGAGAAATAGGTTCAGTAATTGGTTTGCATAGAATATGACCTAGCCATCGAACCTGCTGTTGCTTTATTCTTGTAGAGAACTTGTGGGGTACGGTTGGTGATGCTGTAGACAAATTTGTTGGTAACATGG
+
G#<<GGGGIIAGGIIGGGIIIIGGGGAGGIIGGGGGGGGGGGAGIIGGGGIIIGGGGGGGGIAGGGGIIIIGGGGGGGIIGGGGGAGGGIIIIIIIGGGGIIIIIIIGGGGGGIGGGGGGGAAAGGGGGAGGGGGGGA.G.GGGG.AGAGGGGGGGIGGGAGGG.AG<<7<GGAGG.GG.GGIIIGGGAA.GGGGA.AG
@HSQ-7001360:236:H3L3YBCXX:2:1101:1217:2131 2:N:0:ATCACGATCTCG
TGCAATACCTGAAAGAAACAACAGGTTTTTAGCTGATTACAGAACAAATGAAAAACGGTTTTGACAGCTTTACAACTTCATGCTATCACATTATCCTTGGCCCATCAAGCGAATAGACCATGTTACCAACAAATTTGTCTACAGCATCACCAACCGTACCCCACAAGTTCTCTACAAGAATAAAGCAACAGCAGGTTCGATGGCTAGGTCAT
+
GGGGGGGGGIIGGIIGGGIGIIGGGGAGGIGGGGIGIIGG.GAGIIGGGGGIAGGIIGGIGIG.<AGGGIGIIIGAAGGGIIIIGIGGGIIIIIGGIIGGIGGGGIIGGIIIIIGGGGGGGGGGGGIIGIIIIGGGIIGIGIGGGGGIGIGGGIGAG.GGGGGIIGGAAGAGG.GGAA.GGG.GGGI..7GGIGGGGGG.A..7<.<G.G..
@HSQ-7001360:236:H3L3YBCXX:2:1101:1172:2135 2:N:0:ATCACGATCTCG
NAAATTTGACAAAGAGTTCCAAGAATACTTTGAATTGCCGTCGAATATACCAAATATACAATTTCTTGTTTTGTTTGTTGCGCAATCTAGTGAAATCATGATCAAAAGGGCTAAAATGCTACTCTGCATGGTTAAA
+
#<GGGIIIIIIIIGGGGIIIIIIIIGGGIIIIIGGIIIGGIIIGIIGGGGGGIIIIIIIIGGIIIIIIIIIIIIIIIIIIIIIGGGIIGAGGGGGGGGIIGGIIIGGGIIIIIIIIIIIIGIIIIGIIGGGGIGGG
@HSQ-7001360:236:H3L3YBCXX:2:1101:1248:2143 1:N:0:ATCACGATCTCG
AATTAGCACCTGCATTCGGTAATGCCAGGATCAGAAAATATTGAGTTCGGAAATTGAATTATGGAAATATCTGAGGCAAACGTTTTGGTCAATCTGTCTTGGTGTTTTGAACAAACTTTGATGATTATCCGTTCTCTACCAGTTACTCAAAGCGGCAATTTTTATTCGCAATACAATTGATTTCTCATTCATATTTCTGTGGATTTTAAAAAAATCACTTTATCCTGTATTAGCTTGAATGCAGATTTCAT
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGGIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIGIIIIIIIIGIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIGGGGGIGGGGGIIIIIIIIIIGIGGIIIIIGGGGGIGIIIGIIGIIIIIIG
```

Note that I am not entirely confident that the filtering pipeline from above is bug free - noting the `take 2` in my filename `dp.2pass_take_two.fq`, the 1st time I ran the pipeline I got a different error in `split-paired-reads.py`, indicating that the length of my sequence did not equal the length of the quality score, which indeed was the case. I was running this time to confirm that ?bug, but seem to have another issue. 

Let me know what other info would be helpful

**Comment by macmanes** [comment]
Here is the initial error I was talking about above. Processed identically. 

```
split-paired-reads.py dp.2pass.fq

|| This is the script split-paired-reads.py in khmer.
|| You are running khmer version 2.0-rc3+66.g94d679f
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||
|| Please see http://khmer.readthedocs.org/en/latest/citations.html for details.

... 0
... 10000
... 20000
... 30000
... 40000
... 50000
... 60000
... 70000
... 80000
... 90000
... 100000
... 110000
... 120000
... 130000
... 140000
... 150000
... 160000
... 170000
... 180000
... 190000
... 200000
... 210000
... 220000
... 230000
... 240000
... 250000
... 260000
... 270000
... 280000
... 290000
Traceback (most recent call last):
  File "/usr/local/bin/split-paired-reads.py", line 4, in <module>
    __import__('pkg_resources').run_script('khmer==2.0rc3+66.g94d679f', 'split-paired-reads.py')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 735, in run_script
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1652, in run_script
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/EGG-INFO/scripts/split-paired-reads.py", line 176, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/EGG-INFO/scripts/split-paired-reads.py", line 151, in main
    for index, is_pair, record1, record2 in paired_iter:
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0rc3+66.g94d679f-py2.7-linux-x86_64.egg/khmer/utils.py", line 149, in broken_paired_reader
    for record in screed_iter:
  File "/usr/local/lib/python2.7/dist-packages/screed-0.9-py2.7.egg/screed/fastq.py", line 60, in fastq_iter
    raise IOError('sequence and quality strings must be '
IOError: sequence and quality strings must be of equal length
```

truncated fastq from `dp.2pass.fq`:

```
@HSQ-7001360:236:H3L3YBCXX:2:1103:1988:93963 1:N:0:ATCACGATCTCG
CCCCCTAAATCTAATAATTCTTACATTGTCAGCCGATTCATAAAGGTGCTCGCTGAAGGTCAAGTCGAAGTGCGACCACTTAACAAGATTTTCCCCCAAAATATGGATGGCTCTGGCACAAAGATGTTCATATACCAT
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIG
```

original entry from `R1.fq`

```
@HSQ-7001360:236:H3L3YBCXX:2:1103:1988:93963 1:N:0:ATCACGATCTCG
CCCCCTAAATCTAATAATTCTTACATTGTCAGCCGATTCATAAAGGTGCTCGCTGAAGGTCAAGTCGAAGTGCGACCACTTAACAAGATTTTCCCCCAAAATATGGATGGCTCTGGCACAAAGATGTTCATATACCATTATGAACACTTTTATAAGGAATAATTCAGAAACGTTGCGTTGAAAGTGCATGTTTTTTGTGAAGACAGTGAAATATCGTGCCGATGTCGTGGCGCCAGTCGAGTTGTCGTTGT
+
GGGGGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIGGIIIIIIIIIIIIIGIIIIIIIIIIIIIIIIIIIGIIIIIIIIIGIGIIIIIIIIIIIA
```

**Comment by mr-c** [comment]
Agreed that whatever lead to the read having mismatched quality and sequence strings is a bug

**Comment by mr-c** [comment]
Try the following:

```
  -0 output_orphaned, --output-orphaned output_orphaned
                        Allow "orphaned" reads and extract them to this file
                        (default: None)
```

**Comment by macmanes** [comment]
I'm in the process of breaking down the pipe command string to see if I can narrow it down to something.. Also seeing if I can reproduce this in a smaller test dataset.

**Comment by mr-c** [comment]
*nod* Thanks

On Tue, Aug 25, 2015 at 4:27 PM Matt MacManes <notifications@github.com>
wrote:

> I'm in the process of breaking down the pipe command string to see if I
> can narrow it down to something.. Also seeing if I can reproduce this in a
> smaller test dataset.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dib-lab/khmer/issues/1276#issuecomment-134769546>.
>
-- 
Michael R. Crusoe: Programmer & Bioinformatician crusoe@ucdavis.edu
The lab for Data Intensive Biology; University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by ctb** [comment]
On Tue, Aug 25, 2015 at 03:53:23PM -0700, Matt MacManes wrote:
> I thought with `2.0-rc3+66.g94d679f` and `screed version 0.9` that all tools could take broken interleaved? Anyway, seems that `split-paired-reads.py` does not.. When processing files like this:

Hi Matt,

after some discussion, we decided that there was no reasonable expectation
that split-paired-reads should handle broken-paired -- see 

https://github.com/dib-lab/khmer/issues/847

for info.  The proper approach would be

interleave-reads | normalize-by-median | extract-paired-reads.py -s /dev/null | split-paired-reads

Neither our docs nor our recipes hav really caught up with this so...
working on it.  Apologies for the confusion.

best,
--titus

**Comment by macmanes** [comment]
sounds good - tho, the `--output-orphaned` flag that @mr-c suggested works perfectly...

**Comment by mr-c** [comment]
@macmanes Where do you recommend we augment our documentation to better explain this?

**Comment by standage** [comment]
The documentation for these scripts is pretty clear IMO. Feel free to re-open if you have a specific suggestion for improvement.
