### ISSUE TITLE
No streaming for abundance-dist-single.py

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1312]
Using

```
|| This is the script abundance-dist-single.py in khmer.
|| You are running khmer version 2.0+21.g3b08291
|| You are also using screed version 0.9
```

called like this:

```
interleave-reads.py ~/reads/kidney.1.fq.gz ~/reads/kidney.2.fq.gz \
| abundance-dist-single.py --threads 8 -M 2000000000 -k 25 - reads.hist
```

Get this error - :( 

```
... 7500000 pairs
final: interleaved 7531918 pairs
output written to block device
Total number of unique k-mers: 149946670
preparing hist from -...
consuming input, round 2 -- -
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0+21.g3b08291-py2.7-linux-x86_64.egg/EGG-INFO/scripts/abundance-dist-single.py", line 160, in __do_abundance_dist__
    read_parser, tracking)
OSError: Generic StreamReadError error

Traceback (most recent call last):
  File "/usr/local/bin/abundance-dist-single.py", line 4, in <module>
    __import__('pkg_resources').run_script('khmer==2.0+21.g3b08291', 'abundance-dist-single.py')
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 735, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1652, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0+21.g3b08291-py2.7-linux-x86_64.egg/EGG-INFO/scripts/abundance-dist-single.py", line 217, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/khmer-2.0+21.g3b08291-py2.7-linux-x86_64.egg/EGG-INFO/scripts/abundance-dist-single.py", line 181, in main
    assert len(abundance_lists) == args.threads, len(abundance_lists)
AssertionError: 7
```

= bummer

**Comment by ctb** [comment]
Yes, this is a 2-pass algorithm.  No other way to do it.

**Comment by ctb** [comment]
It would be possible to generate an approximate k-mer abundance distribution in a single pass by counting k-mers from some initial number of reads and then collecting k-mers that occur later in the stream to count.  But, fundamentally, the khmer data structures don't (yet) support enumeration of k-mers which blocks a single-pass approach.  (#689 is kind of relevant)
