### ISSUE TITLE
Installation can use wrong nosetests

### ISSUE THREAD

**Issue by rob-p** [dib-lab/khmer#1318]
I was following the [khmer v2.0 install instructions](https://khmer.readthedocs.org/en/v2.0/user/install.html) on OSX 10.10.5.  Everything seems to work fine until the point when I actually try to run the tests:

```
(khmerEnv)->nosetests khmer --attr '!known_failing,!huge'
E
======================================================================
ERROR: Failure: ImportError (No module named khmer)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/Library/Python/2.7/site-packages/nose/util.py", line 312, in resolve_name
    module = __import__('.'.join(parts_copy))
ImportError: No module named khmer

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

After some fiddling around, it became clear that this is because the virtual environment was using the system install of `nosetests`, which was failing to find the `khmer` package.  The simple solution was to first install `nosetests`:

```
(khmerEnv)->khmerEnv/bin/pip2.7 install nose
```

and then to run the tests with the resulting nosetests executable directly:

```
(khmerEnv)->khmerEnv/bin/nosetests khmer --attr '!known_failing,!huge'
```

This seems to work, but there is a test which fails.

```
............................................................................................................................................................................................................................................................................................................................................................F...SSSSSSSSSS.......................................................................................................................................................................................................................................................
======================================================================
FAIL: khmer.tests.test_read_parsers.test_read_pair_iterator_in_error_mode_xfail
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rob/khmer/khmerEnv/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/rob/khmer/khmerEnv/lib/python2.7/site-packages/khmer/tests/test_read_parsers.py", line 364, in test_read_pair_iterator_in_error_mode_xfail
    assert "Invalid read pair" in str(exc), str(exc)
AssertionError

----------------------------------------------------------------------
Ran 609 tests in 34.041s

FAILED (SKIP=10, failures=1)
```

Is this failure a known-issue, or should I open up a separate issue for it?

**Comment by ctb** [comment]
Thanks, Rob, we have to go through the install documentation more closely,
it seems!

The error is a known problem on Mac OS X.  Links when I get a chance.

best,
--titus

**Comment by mr-c** [comment]
@rob-p I'm glad you were able to fix the nosetest problem. As noted in the docs you linked to "If you are running an OSX system you should also add !linux to prevent linux-specific tests from failing."

So `khmerEnv/bin/nosetests khmer --attr '!known_failing,!huge,!linux'` should work. Perhaps we should make that more prominent?

**Comment by standage** [comment]
This seems resolved, and in any case we have moved to py.test. Closing for now.
