### ISSUE TITLE
make install-dependencies fails on HPC

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#1335]
I get this exception:

Exception:
Traceback (most recent call last):
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/commands/install.py", line 305, in run
    wb.build(autobuilding=True)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/wheel.py", line 705, in build
    self.requirement_set.prepare_files(self.finder)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/req/req_set.py", line 491, in _prepare_file
    session=self.session)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/download.py", line 825, in unpack_url
    session,
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/download.py", line 673, in unpack_http_url
    from_path, content_type = _download_http_url(link, session, temp_dir)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/download.py", line 857, in _download_http_url
    stream=True,
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/download.py", line 373, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/_vendor/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/home/mansourt/env/lib/python2.7/site-packages/pip/_vendor/requests/adapters.py", line 424, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='ci.oxli.org', port=8080): Max retries exceeded with url: /userContent/sphinxcontrib-autoprogram-0.1.1-khmerdev-20140331.tar.gz (Caused by ProtocolError('Connection aborted.', error(101, 'Network is unreachable')))

**Comment by drtamermansour** [comment]
More information:
I am trying to install the github version by cloning the repository. I am using the most recent version of virtualenv (13.1.2). Also I load GNU/4.7.1 because I know that the default GNU/4.4.5 does not allow khmer installation
