### ISSUE TITLE
pip installation on HPC does not pass tests

### ISSUE THREAD

**Issue by drtamermansour** [dib-lab/khmer#1336]
I installed khmer on HPC according to the guidelines on http://khmer.readthedocs.org/en/v2.0/user/install.html
The testing step failed with this error

ERROR: khmer.tests.test_scripts.test_check_space
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/software/Python/2.7.2--GCC-4.4.5/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/opt/software/Python/2.7.2--GCC-4.4.5/lib/python2.7/site-packages/khmer/tests/test_scripts.py", line 68, in test_check_space
    ['', utils.get_test_data('test-abund-read-2.fa')], False)
  File "/opt/software/Python/2.7.2--GCC-4.4.5/lib/python2.7/site-packages/khmer/kfile.py", line 150, in check_space
    sys.exit(1)
SystemExit: 1

----------------------------------------------------------------------
Ran 609 tests in 44.232s

**Comment by drtamermansour** [comment]
This was a temporary issue related to the home disk space of HPC. I communicated with with and issue was solved
