### ISSUE TITLE
Syntax error in text_read_parsers

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1359]
I can reproduce the error below with the following configurations.

- Python 3.5, OS X
- Python 3.4, OS X
- Python 3.5, Ubuntu 16.04

```
======================================================================
ERROR: Failure: SyntaxError (invalid syntax (test_read_parsers.py, line 344))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/standage/Software/kenv34/lib/python3.4/site-packages/nose/failure.py", line 39, in runTest
    raise self.exc_val.with_traceback(self.tb)
  File "/Users/standage/Software/kenv34/lib/python3.4/site-packages/nose/loader.py", line 418, in loadTestsFromName
    addr.filename, addr.module)
  File "/Users/standage/Software/kenv34/lib/python3.4/site-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/Users/standage/Software/kenv34/lib/python3.4/site-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/Users/standage/Software/kenv34/lib/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/Users/standage/Software/kenv34/lib/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1467, in exec_module
  File "<frozen importlib._bootstrap>", line 1572, in get_code
  File "<frozen importlib._bootstrap>", line 1532, in source_to_code
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/Users/standage/Software/khmer/tests/test_read_parsers.py", line 344
    matches = [(rp1, rp2) for rp1, rp2 in read_pairs_1, read_pairs_2
                                                      ^
SyntaxError: invalid syntax
```

Oddly enough, I don't see the error in Python 2.7 on OS X, and I get a different error for Python 2.7 on Ubuntu.

**Comment by ctb** [comment]
Should be fixed in #1361.
