### ISSUE TITLE
`test_countgraph.py:test_load_truncated` core dumps in Fedora 23

### ISSUE THREAD

**Issue by standage** [dib-lab/khmer#1387]
Walking through the function interactively, it's fine until the following.

```
>>> _ = khmer.load_countgraph(truncpath)
terminate called after throwing an instance of 'std::ios_base::failure'
  what():  basic_ios::clear
Aborted (core dumped)
```

I don't have much experience with C++ exception handling, and therefore not much intuition for what's happening at that level. At the Python level, it's clear that the the `load_countgraph` command is supposed to evoke some OS error, which Python is supposed to wrap and handle. Why this works on Jenkins and my laptop but not on Fedora is a mystery to me.

**Comment by ctb** [comment]
@standage, I've noticed that more recent versions of gcc are better about
flagging certain kinds of issues, including memory leaks.  In this case it
doesn't look like that kind of issue, but by analogy it's likely to be
something version related :)

What version of gcc are you using?

Do you want some help tracking down the line number? You should be able to
do something like 'gdb python' and then 'python -m pytest ...', followed
by a 'where' after the crash, to see which line, exactly, is triggering
the error.

Wherever the exception is being raised, it seems like it isn't being properly
caught and transformed into a khmer_file_exception in
CountingHashFileReader::CountingHashFileReader in counting.cc.

**Comment by standage** [comment]
> What version of gcc are you using?

5.3.1

> You should be able to do something like 'gdb python' and then 'python -m pytest ...', followed by a 'where' after the crash, to see which line, exactly, is triggering the error.

How long does `where` typically take to print out the stack trace? The first dozen or so items print out very quickly and then the stack trace printing slows down considerably. I've run gdb several times, and each time I just quit the stack trace printing after 10-15 minutes / 50-60 items. Should I wait longer?

Here's a sample of what I see: looks much more like core Python code than khmer code.

```
(gdb) run -m pytest tests/test_countgraph.py
Starting program: /home/standage/kenv3/bin/python -m pytest tests/test_countgraph.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
========================================= test session starts ==========================================
platform linux -- Python 3.4.3, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/standage/kenv3/bin/python
cachedir: .cache
rootdir: /home/standage/khmer, inifile: pytest.ini
collecting 0 itemsDetaching after fork from child process 11569.
Detaching after fork from child process 11570.
collected 85 items 

tests/test_countgraph.py::test_count_1 PASSED
tests/test_countgraph.py::test_count_2 PASSED
tests/test_countgraph.py::test_revhash_1 PASSED
tests/test_countgraph.py::Test_Countgraph::test_failed_get PASSED
tests/test_countgraph.py::Test_Countgraph::test_collision_1 PASSED
tests/test_countgraph.py::Test_Countgraph::test_collision_2 PASSED
tests/test_countgraph.py::Test_Countgraph::test_collision_3 PASSED
tests/test_countgraph.py::test_get_raw_tables PASSED
tests/test_countgraph.py::test_get_raw_tables_view PASSED
tests/test_countgraph.py::test_3_tables PASSED
tests/test_countgraph.py::test_simple_median PASSED
tests/test_countgraph.py::test_median_too_short PASSED
tests/test_countgraph.py::test_median_at_least PASSED
tests/test_countgraph.py::test_median_at_least_single_gt PASSED
tests/test_countgraph.py::test_median_at_least_single_lt PASSED
tests/test_countgraph.py::test_median_at_least_odd_gt PASSED
tests/test_countgraph.py::test_median_at_least_odd_lt PASSED
tests/test_countgraph.py::test_median_at_least_even_gt PASSED
tests/test_countgraph.py::test_median_at_least_even_lt PASSED
tests/test_countgraph.py::test_median_at_least_comp PASSED
tests/test_countgraph.py::test_median_at_least_exception PASSED
tests/test_countgraph.py::test_get_kmer_counts_too_short PASSED
tests/test_countgraph.py::test_get_kmer_hashes_too_short PASSED
tests/test_countgraph.py::test_get_kmers_too_short PASSED
tests/test_countgraph.py::test_get_kmer_counts PASSED
tests/test_countgraph.py::test_get_kmer_hashes PASSED
tests/test_countgraph.py::test_get_kmers PASSED
tests/test_countgraph.py::test_save_load_occupied PASSED
tests/test_countgraph.py::test_save_load PASSED
tests/test_countgraph.py::test_load_truncated 
Program received signal SIGABRT, Aborted.
0x00007ffff6c97a28 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
55	  return INLINE_SYSCALL (tgkill, 3, pid, selftid, sig);
(gdb) where
#0  0x00007ffff6c97a28 in __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:55
#1  0x00007ffff6c9962a in __GI_abort () at abort.c:89
#2  0x00007fffeae50add in __gnu_cxx::__verbose_terminate_handler ()
    at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007fffeae4e936 in __cxxabiv1::__terminate (handler=<optimized out>)
    at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007fffeae4e981 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007fffeae4eb99 in __cxxabiv1::__cxa_throw (obj=obj@entry=0x555555af6c70, 
    tinfo=0x7fffeb135740 <typeinfo for std::ios_base::failure>, 
    dest=0x7fffeae5e890 <std::ios_base::failure::~failure()>)
    at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x00007fffeae779a6 in std::__throw_ios_failure (__s=__s@entry=0x7fffeaefe427 "basic_ios::clear")
    at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:126
#7  0x00007fffeaeb538a in std::basic_ios<char, std::char_traits<char> >::clear (this=<optimized out>, 
    __state=<optimized out>)
    at /usr/src/debug/gcc-5.3.1-20160406/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_ios.tcc:48
#8  0x00007fffeaeb8bb9 in std::basic_ios<char, std::char_traits<char> >::setstate (__state=6, 
    this=<optimized out>)
    at /usr/src/debug/gcc-5.3.1-20160406/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/basic_ios.h:158
#9  std::istream::read (this=this@entry=0x7fffffff6520, __s=__s@entry=0x7fffffff6730 "@\377\257UUU", 
    __n=__n@entry=4)
    at /usr/src/debug/gcc-5.3.1-20160406/obj-x86_64-redhat-linux/x86_64-redhat-linux/libstdc++-v3/include/bits/istream.tcc:671
#10 0x00007fffeb197fd3 in khmer::CountingHashFileReader::CountingHashFileReader (this=<optimized out>, 
    infilename="/tmp/khmertest_eg3i6nu5/trunc.ht", ht=...) at lib/counting.cc:364
#11 0x00007fffeb19ba9b in khmer::CountingHashFile::load (infilename=..., ht=...) at lib/counting.cc:304
#12 0x00007fffeb167570 in hashtable_load (me=<optimized out>, args=<optimized out>)
    at khmer/_khmer.cc:1476
#13 0x00007ffff7a656f1 in call_function (oparg=<optimized out>, pp_stack=0x7fffffff6930)
---Type <return> to continue, or q <return> to quit---
    at /usr/src/debug/Python-3.4.3/Python/ceval.c:4266
#14 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x7fffe9fcf048, for file /home/standage/khmer/khmer/__init__.py, line 95, in load_countgraph (filename='/tmp/khmertest_eg3i6nu5/trunc.ht', countgraph=<_khmer.Countgraph at remote 0x7fffea975170>), throwflag=throwflag@entry=0) at /usr/src/debug/Python-3.4.3/Python/ceval.c:2862
#15 0x00007ffff7a64eeb in fast_function (nk=<optimized out>, na=<optimized out>, n=1, 
    pp_stack=0x7fffffff6a70, func=<optimized out>) at /usr/src/debug/Python-3.4.3/Python/ceval.c:4363
#16 call_function (oparg=<optimized out>, pp_stack=0x7fffffff6a70)
    at /usr/src/debug/Python-3.4.3/Python/ceval.c:4291
#17 PyEval_EvalFrameEx (
    f=f@entry=Frame 0x555555b03c18, for file /home/standage/khmer/tests/test_countgraph.py, line 645, in test_load_truncated (inpath='/home/standage/khmer/tests/test-data/random-20-a.fa', savepath='/tmp/khmertest_uv4mpcyf/save.ht', truncpath='/tmp/khmertest_eg3i6nu5/trunc.ht', sizes=[199, 197, 193], hi=<_khmer.Countgraph at remote 0x7fffea975310>, data=b'OXLI\x04\x01\x00\x0c\x00\x00\x00\x03\xc7\x00\x00\x00\x00\x00\x00\x00\xc7\x00\x00\x00\x00\x00\x00\x00\x17\x14\x16\x17\x18\x15\x1a\x19\x1f\x17\x1b\x11\x15\x1a\x19\x19\x16\x1b\x13\x1c\x19\x15\x11\x16\x19\x10\x1f\x15\x1e\x17\x10\x17\x14\x12\x18#\x11!\x13\x1a\x11\x1b\x17\x17\x17\x19\x11\x13\x16\x16\x1b!\x19"\x14\x1b\x14\x1c\x1a\x19\x14\x15\x1a\x18\x19%\x1c\x1d\x1e\x14\x0f"(\x15\x1d\x17\x1b\x1c\x1b\x14 \x0c\x1f\x1d\x1c\x1d\x15\x17\x0f\x17\x13\x1f\x18\x1a\x17\x15\x1c\x1c\x1e\x1d\x13\x18\x16\x1b\x19\x1d\x1f\x10\x19\x14 \x12\x14\x18\x1b\x17\x12\x10\x1b\x13\x1c\x17\x14\x1b\x1a\x12\x14\x17\x15\x1b\x1e\x1a\x0f\x16\x1a\x14\x1c\x11\x17!\x15\x14\x1a\x11\x1f%\x19\x11\x1a\x15\x17\x19\x13\x...(truncated), throwflag=throwflag@entry=0) at /usr/src/debug/Python-3.4.3/Python/ceval.c:2862
#18 0x00007ffff7a666d6 in PyEval_EvalCodeEx (_co=<code at remote 0x7fffeb8fc0c0>, 
    globals=<optimized out>, locals=locals@entry=0x0, args=args@entry=0x7ffff7f8a060, argcount=0, 
    kws=kws@entry=0x7ffff7f8a060, kwcount=0, defs=0x0, defcount=0, kwdefs=0x0, closure=0x0)
    at /usr/src/debug/Python-3.4.3/Python/ceval.c:3617
#19 0x00007ffff79d6835 in function_call (func=<function at remote 0x7fffea987a60>, arg=(), kw={})
    at /usr/src/debug/Python-3.4.3/Objects/funcobject.c:632
#20 0x00007ffff79addb1 in PyObject_Call (func=func@entry=<function at remote 0x7fffea987a60>, 
    arg=arg@entry=(), kw=kw@entry={}) at /usr/src/debug/Python-3.4.3/Objects/abstract.c:2040
#21 0x00007ffff7a61b01 in ext_do_call (nk=<optimized out>, na=0, flags=<optimized out>, 
    pp_stack=0x7fffffff6d58, func=<function at remote 0x7fffea987a60>)
    at /usr/src/debug/Python-3.4.3/Python/ceval.c:4590
```

**Comment by ctb** [comment]
On Mon, Jun 20, 2016 at 10:49:14AM -0700, Daniel Standage wrote:
> > What version of gcc are you using?
> 
> 5.3.1
> 
> > You should be able to do something like 'gdb python' and then 'python -m pytest ...', followed by a 'where' after the crash, to see which line, exactly, is triggering the error.
> 
> How long does `where` typically take to print out the stack trace? The first dozen or so items print out very quickly and then the stack trace printing slows down considerably. I've run gdb several times, and each time I just quit the stack trace printing after 10-15 minutes / 50-60 items. Should I wait longer?

I've never seen that. I have no idea!

You will see core Python code b/c we are a CPython library.

**Comment by standage** [comment]
I've been updating and compiling khmer on Fedora for several months now without seeing this problem again. Closing for now.
