### ISSUE TITLE
Reordering reads after trim-low-abund.py

### ISSUE THREAD

**Issue by ctSkennerton** [dib-lab/khmer#1404]
I have trimmed my data using `trim-low-abund.py` using the following command:
```
trim-low-abund.py -C 3 -Z 20 -N 5 -x 4e10 -s 7086_countgraph.cg --gzip *gz
```
It produces a *.abundtrim file for each of my input files however it appears that the order of the reads is different between the two files. I tried using the script `extract-paired-reads.py` to make files that reorder the pairs and split out the singles using the following:
```
gunzip -c *abundtrim | extract-paired-reads.py -p 7086_S82_L007_pe.fastq -s 7086_S82_L007_se.fastq
```
This runs but throws an exception at the end
```
... 164700000
Traceback (most recent call last):
  File "/media/eclipse/orphanlab/anaconda3/bin/extract-paired-reads.py", line 186, in <module>
    main()
  File "/media/eclipse/orphanlab/anaconda3/bin/extract-paired-reads.py", line 175, in main
    raise Exception("no paired reads!? check file formats...")
Exception: no paired reads!? check file formats...
```
Using grep on the first five reads, I can find some of them in both of the abundtrim files so I'm wondering why `extract-paired-reads.py` doesn't work? (Or perhaps it isn't expected to and I should be using a different method?)

**Comment by standage** [comment]
What does the first line of each Fastq record look like? Perhaps it is not declaring the pairing in a way khmer can recognize?

**Comment by ctSkennerton** [comment]
A couple of examples:
```
@J00113:120:H7JTNBBXX:7:1101:11028:3090 1:N:0:GTTTCG
@J00113:120:H7JTNBBXX:7:1101:5020:4673 1:N:0:GTTTCG
```
Pretty sure it was sequenced on a HiSeq3000 (at UC Davis)

**Comment by standage** [comment]
That looks like the Casava 1.8 format, which should be supported.

Is there any way you can provide a small subset of the data the reproduces the problem?

**Comment by ctb** [comment]
Connor, is this the data set I downloaded? I think so.

**Comment by ctSkennerton** [comment]
Yep, this is sample 7086 which you sequences for us, so I think you should have the full dataset

**Comment by standage** [comment]
@ctb, is this data generally accessible to lab members?

**Comment by ctb** [comment]
(Apologies for delay -- course is keeping me busy!)

Hi @ctSkennerton, the read pairing format looks legit for khmer. My guess is that you're not interleaving the reads first -- I'm running

```
interleave-reads.py *.gz | trim-low-abund.py -C 4 -Z 20 -M 12e9 -k 21 - --gzip -o 7086_S82_L007.abundtrim.fq.gz
```
to do that.  I'll let you know how it turns out!

@standage, you can grab the reads here: athyra.idyll.org/~t/transfer/7086.fq.gz

It seems like a bit of a UX problem that trim-low-abund will take R1/R2 files separately and be quiet about it. Sigh. This whole read pairing thing is a nightmare.

**Comment by ctSkennerton** [comment]
I see, yeah didn't realize that the reads needed to be interleaved. Will this change affect the trimming of the data if the reads are interleaved or not?

**Comment by ctb** [comment]
It shouldn't affect the trimming, but the data will be out of order for
later processing and code like extract-paired-ends won't work.  If
done interleaved, pairs will stay together in the stream and then it's
easy to get the PE/SE, or left/right, or whatever you want.

**Comment by ctb** [comment]
My trim-low-abund command finished w/following results:

```
read 364142498 reads, 54621374700 bp
wrote 356565860 reads, 33327218777 bp
looked at 330788594 reads twice (1.91 passes)
removed 7576638 reads and trimmed 220699034 reads (62.69%)
trimmed or removed 38.99%% of bases (21294155923 total)
**
** ERROR: the graph structure is too small for
** this data set.  Increase data structure size
** with --max_memory_usage/-M.
**
** Do not use these results!!
**
** (estimated false positive rate of 0.998; max recommended 0.800)
**
```

Something odd about this data set... need to think a bit more on it. Could it be that there's one pretty dominant set of critters and then a lot of low-abundance microbes? I'm surprised by how many reads were trimmed (indicating lots of high coverage) but how many k-mers there were in there (indicating lots of low-abundance critters).

**Comment by standage** [comment]
I had no problems running `trim-low-abund` on that one data file on my laptop as follows. This is probably a small fraction of a larger dataset though, right?

```
$ wget http://athyra.idyll.org/~t/transfer/7086.fq.gz
$ trim-low-abund.py -C 4 -Z 20 -M 4e9 -k 21 7086.fq.gz --gzip -o 7086_S82_L007.abundtrim.fq.gz

|| This is the script trim-low-abund.py in khmer.
|| You are running khmer version 2.0+201.ga5c3279
|| You are also using screed version 0.9
||
|| If you use this script in a publication, please cite EACH of the following:
||
||   * MR Crusoe et al., 2015. http://dx.doi.org/10.12688/f1000research.6924.1
||   * Q Zhang, S Awad, CT Brown, https://dx.doi.org/10.7287/peerj.preprints.890v1
||
|| Please see http://khmer.readthedocs.io/en/latest/citations.html for details.

PARAMETERS:
 - kmer size =    21 		(-k)
 - n tables =     4 		(-N)
 - max tablesize = 1e+09 	(-x)

Estimated memory usage is 4e+09 bytes (n_tables x max_tablesize)
--------
making countgraph
created temporary directory ./tmp9yqg35k6khmer;
use -T to change location
7086.fq.gz: kept aside 25000 of 25000 from first pass
second pass: looking at sequences kept aside in ./tmp9yqg35k6khmer/7086.fq.gz.pass2
... x 2 25046 ./tmp9yqg35k6khmer/7086.fq.gz.pass2 25000 25046 3756900 0 0
... x 2 27819 ./tmp9yqg35k6khmer/7086.fq.gz.pass2 25000 27819 4172850 1 67
... x 2 31397 ./tmp9yqg35k6khmer/7086.fq.gz.pass2 25000 31397 4709550 4 141
... x 2 41353 ./tmp9yqg35k6khmer/7086.fq.gz.pass2 25000 41353 6202950 25 1820
removing ./tmp9yqg35k6khmer/7086.fq.gz.pass2
removing temp directory & contents (./tmp9yqg35k6khmer)
read 25000 reads, 3750000 bp
wrote 41 reads, 3085 bp
looked at 25000 reads twice (2.00 passes)
removed 24959 reads and trimmed 35 reads (99.98%)
trimmed or removed 99.92%% of bases (3746915 total)
fp rate estimated to be 0.000
output in *.abundtrim
```

**Comment by ctb** [comment]
@ctSkennerton: total number of unique k-mers is 2786486327 *after trimming*. that's *2.8 billion k-mers.* WTH?

**Comment by ctSkennerton** [comment]
Haha, well it's a lot lower than the raw dataset which had *25 Billion* k-mers. Actually, this is one of the most diverse samples we have. Take a look below for the unique 32-mers in all of the metagenomes we have sequenced. (these numbers are all from untrimmed data)

I think though we are starting to get off topic of the original issue of reordering the reads, which I think can be solved by your solution. What I think isn't imeadiately clear when using `extract-paired-reads.py` is that the reads need to be within a certain distance in the file, in my command I just concatenated the files togther so it was all read 1 then all read 2, which it didn't like.
 
![unique kmers](https://cloud.githubusercontent.com/assets/685235/16924431/19157b16-4cd4-11e6-9fe2-ac2a93b6d78f.png)
