### ISSUE TITLE
make-coverage.py key error

### ISSUE THREAD

**Issue by peterdfields** [dib-lab/khmer#1422]
I'm seeing the following error from running make-coverage.py on a bowtie 1 generated sam file.

`Traceback (most recent call last):
  File "/home/peter/bioinformatics/khmer_2.0/khmer/sandbox/make-coverage.py", line 79, in <module>
    main()
  File "/home/peter/bioinformatics/khmer_2.0/khmer/sandbox/make-coverage.py", line 66, in main
    float(mapped_reads) / 1e6
KeyError: 'k99_70222'`

The contig was generated using megahit.

**Comment by standage** [comment]
Thanks for the report @peterdfields!

I'm unfamiliar with the script in question: it's in our sandbox (as opposed to one of our officially supported scripts) and there doesn't seem to be any documentation of the expected input (other than the variable names in the code). Presumably the two arguments are 1) a genomic DNA fasta file and 2) a plain-text SAM file with which to compute coverage?

It's difficult to figure out exactly what's going on without the precise input files. If you could share these that would help, although the file size might complicate that...

**Comment by standage** [comment]
Just a quick thought: does your SAM file have a header? It doesn't look like the `make-coverage.py` script attempts to skip any header lines, so if there are header lines they could potentially cause problems.

**Comment by peterdfields** [comment]
I don't think it's an issue with the sam header but rather with the contig naming system that megahit defaults to. To give you a bit more context I was following along with the following khmer use tutorial: https://khmer-protocols.readthedocs.io/en/ctb/metagenomics/5-mapping-and-quantitation.html

I changed the fasta entry names to an ascending count (so >1, >2, etc.) and the error goes away.

Given the rename changes do you think seeing the output files would be useful? Also, an example fasta entry header is:

>k99_10 flag=1 multi=1.1869 len=297

**Comment by standage** [comment]
The comment about SAM headers was just a shot in the dark. It doesn't look like it's worth looking into.

Maybe the problem is that sometimes the sequence ID is being read as `k99_10` and sometimes it's being read as `k99_10 flag=1 multi=1.1869 len=297`. Changing all the seqIDs to `>1` and so on would certainly make the problem go away. But it should be easy enough to fix to script (or the protocol) to handle this correctly.

Anyone with experience with this protocol want to tackle this? @camillescott @ctb Otherwise, I'll make some time to go through the tutorial and replicate the issue.

**Comment by ctb** [comment]
Looks very much like the problem is in name parsing - screed chooses the sequence name one way (up to the first whitespace) and bowtie is providing the entire name.  @peterdfields can you provide a small test set (just the first 100 or 1000 lines of the two files should be enough)?

**Comment by BrianNoh** [comment]
I was having a similar issue and removing all the spaces in my contig names fixed the error and was able to run.  Here's an example.
>contig-100_0 length_2270 read_count_63132 -- causes error
>contig-100_0length_2270read_count_63132 -- script works
