### ISSUE TITLE
khmer issue with GLIBC on Ubuntu 14.04

### ISSUE THREAD

**Issue by macmanes** [dib-lab/khmer#1499]
Cross posted from dammit issue, based on feedback received there. 

https://github.com/camillescott/dammit/issues/73

Looks like dammit has issues on ubuntu 14.04 related to not having a new version of glibc.. 

```
gcc --version
gcc (Homebrew gcc 5.3.0) 5.3.0

ldd --version
2.19
```

Installing like this:

```
sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
sudo apt-get -y install build-essential git python-pip python-numpy python-matplotlib

# Install LinuxBrew and some software

gem install crb-blast
pip install -U setuptools
pip install pandas
pip install dammit

...
Successfully built dammit khmer doit nose-capturestderr ficus screed bz2file pyinotify configparser docutils MarkupSafe
Installing collected packages: bz2file, screed, khmer, cloudpickle, pyinotify, configparser, doit, imagesize, Pygments, snowballstemmer, alabaster, docutils, babel, MarkupSafe, Jinja2, Sphinx, sphinx-rtd-theme, nose, nose-capturestderr, cycler, pyparsing, matplotlib, ficus, numexpr, dammit
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 Sphinx-1.4.8 alabaster-0.7.9 babel-2.3.4 bz2file-0.98 cloudpickle-0.2.1 configparser-3.5.0 cycler-0.10.0 dammit-0.3 docutils-0.12 doit-0.29.0 ficus-0.3.2 imagesize-0.7.1 khmer-2.0 matplotlib-1.5.3 nose-1.3.4 nose-capturestderr-1.0 numexpr-2.6.1 pyinotify-0.9.6 pyparsing-2.1.10 screed-0.9 snowballstemmer-1.2.1 sphinx-rtd-theme-0.1.9
```

```

$ dammit

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/dammit", line 4, in <module>
    import dammit
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/__init__.py", line 12, in <module>
    import tasks
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/tasks.py", line 18, in <module>
    from khmer import HLLCounter, ReadParser
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/_khmer.so)
```

**Comment by ctb** [comment]
Hi Matt,

could you do:

pip install -v khmer

directly, and send us that output?

thanks!

On Wed, Nov 02, 2016 at 04:33:22AM -0700, Matt MacManes wrote:
> Cross posted from dammit issue, based on feedback received there. 
> 
> https://github.com/camillescott/dammit/issues/73
> 
> Looks like dammit has issues on ubuntu 14.04 related to not having a new version of glibc.. 
> 
> ```
> gcc --version
> gcc (Homebrew gcc 5.3.0) 5.3.0
> 
> ldd --version
> 2.19
> ```
> 
> Installing like this:
> 
> ```
> sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
> sudo apt-get -y install build-essential git python-pip python-numpy python-matplotlib
> 
> # Install LinuxBrew and some software
> 
> gem install crb-blast
> pip install -U setuptools
> pip install pandas
> pip install dammit
> 
> ...
> Successfully built dammit khmer doit nose-capturestderr ficus screed bz2file pyinotify configparser docutils MarkupSafe
> Installing collected packages: bz2file, screed, khmer, cloudpickle, pyinotify, configparser, doit, imagesize, Pygments, snowballstemmer, alabaster, docutils, babel, MarkupSafe, Jinja2, Sphinx, sphinx-rtd-theme, nose, nose-capturestderr, cycler, pyparsing, matplotlib, ficus, numexpr, dammit
> Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 Sphinx-1.4.8 alabaster-0.7.9 babel-2.3.4 bz2file-0.98 cloudpickle-0.2.1 configparser-3.5.0 cycler-0.10.0 dammit-0.3 docutils-0.12 doit-0.29.0 ficus-0.3.2 imagesize-0.7.1 khmer-2.0 matplotlib-1.5.3 nose-1.3.4 nose-capturestderr-1.0 numexpr-2.6.1 pyinotify-0.9.6 pyparsing-2.1.10 screed-0.9 snowballstemmer-1.2.1 sphinx-rtd-theme-0.1.9
> ```
> 
> ```
> 
> $ dammit
> 
> Traceback (most recent call last):
>   File "/home/linuxbrew/.linuxbrew/bin/dammit", line 4, in <module>
>     import dammit
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/__init__.py", line 12, in <module>
>     import tasks
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/tasks.py", line 18, in <module>
>     from khmer import HLLCounter, ReadParser
>   File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/__init__.py", line 42, in <module>
>     from khmer._khmer import Countgraph as _Countgraph
> ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/_khmer.so)
> ``` 
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/dib-lab/khmer/issues/1499
-- 
C. Titus Brown, ctbrown@ucdavis.edu

**Comment by macmanes** [comment]
```
$ pip install -v khmer

Requirement already satisfied (use --upgrade to upgrade): khmer in /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): bz2file in /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages (from khmer)
Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages (from khmer)
Cleaning up...

```

**Comment by ctb** [comment]
Sorry, could you do:

```
pip uninstall khmer
pip install -v khmer
```

(I'm trying to figure out what version of khmer dammit is asking for, and also
figure out why it seems like it's not recompiling it on your linux box.)

**Comment by macmanes** [comment]
```
Collecting khmer
  1 location(s) to search for versions of khmer:
  * https://pypi.python.org/simple/khmer/
  Getting page https://pypi.python.org/simple/khmer/
  Looking up "https://pypi.python.org/simple/khmer/" in the cache
  Current age based on date: 27
  Freshness lifetime from max-age: 600
  Freshness lifetime from request max-age: 600
  The response is "fresh", returning cached response
  600 > 27
  Analyzing links from page https://pypi.python.org/simple/khmer/
    Skipping link https://pypi.python.org/packages/22/37/6c6fb54d9b8feb8a64e52e6e16cd409bc47d8240294caf8449fac6523f64/khmer-2.0-cp33-cp33m-macosx_10_6_x86_64.whl#md5=a103216e12e0eb12484c4c93304e9900 (from https://pypi.python.org/simple/khmer/); it is not
compatible with this Python
    Found link https://pypi.python.org/packages/31/8f/7063987e7713dfbcd05bc53e4778c2284e3ea905112fc97d83d03afa60d9/khmer-0.8.tar.gz#md5=5da3d860f91e2795e5db17a4404e1b11 (from https://pypi.python.org/simple/khmer/), version: 0.8
    Skipping link https://pypi.python.org/packages/36/cb/4a1638d5ca5a9b0d53c1b5484cefdcda9f3079bfb0b92e2ae2fac6d83bfd/khmer-2.0-cp35-cp35m-macosx_10_6_intel.whl#md5=12e37dbda998f1c347fe58829224ee58 (from https://pypi.python.org/simple/khmer/); it is not c
ompatible with this Python
    Found link https://pypi.python.org/packages/3a/bd/b1eb804f77e6ea99f9db02688c1474628d844e2f59a4f77d7bc00f8c990b/khmer-0.7.tar.gz#md5=4208eee78fa0f0df53421a231af39b14 (from https://pypi.python.org/simple/khmer/), version: 0.7
    Skipping link https://pypi.python.org/packages/41/7a/d94ad453d04782d82aebe7825ef4f1a38fc9e3374b0b3cfe9b1c5400482e/khmer-1.3-cp27-none-macosx_10_10_intel.whl#md5=a2ee1937103825223ffa566818a82c61 (from https://pypi.python.org/simple/khmer/); it is not c
ompatible with this Python
    Skipping link https://pypi.python.org/packages/4e/6c/33badfa2550b73b7f037afa2e37aa09b7506b5dbd58175b0c24f40ed8179/khmer-1.0-cp27-none-macosx_10_9_intel.whl#md5=84054e41455743f294c85198c81e6ef0 (from https://pypi.python.org/simple/khmer/); it is not co
mpatible with this Python
    Found link https://pypi.python.org/packages/4e/73/cebb5f4952d79693ddd5c8a9efac21883f1b4cdff1d046adb2df1f2070bd/khmer-1.0.1.tar.gz#md5=f7566c0695ed77da6edf6891ac0de43f (from https://pypi.python.org/simple/khmer/), version: 1.0.1
    Found link https://pypi.python.org/packages/52/3b/2c52a13937197391775f274ed75b4a33b2d7767a904faaf4032e14e10a55/khmer-2.0.tar.gz#md5=1f610abd021254e21b082179a100cd39 (from https://pypi.python.org/simple/khmer/), version: 2.0
    Found link https://pypi.python.org/packages/5a/91/eb0c9a5fdab42699c56b8c60d0d02e806f4d4d42f809061eb9a1a9a59dfa/khmer-1.4.tar.gz#md5=ef11131b85e7b607d0a74be2d00a8851 (from https://pypi.python.org/simple/khmer/), version: 1.4
    Skipping link https://pypi.python.org/packages/5c/44/1d4273abe1bf162cd1a8c8d5424cec23e65971f90951659a0b590beaf364/khmer-1.4.1-cp27-none-macosx_10_10_intel.whl#md5=70d6d4f31fcbb5292fd27ce5819ed4f8 (from https://pypi.python.org/simple/khmer/); it is not
 compatible with this Python
    Skipping link https://pypi.python.org/packages/5d/f6/791f79f68be58cb20c6426726063d742b3dd778b222873cb9f01ab65bc09/khmer-2.0-cp27-none-macosx_10_6_intel.whl#md5=ebb505271e272981e925493232f3dd0d (from https://pypi.python.org/simple/khmer/); it is not co
mpatible with this Python
    Found link https://pypi.python.org/packages/5e/16/15243a0612c798595e8dd8bdf0477a7ce065929b9de5dbfebdf461006f05/khmer-1.4.1.tar.gz#md5=620526ca403d09ed688267f425035fc5 (from https://pypi.python.org/simple/khmer/), version: 1.4.1
    Found link https://pypi.python.org/packages/67/d0/334f8bba7befb5d671bf5663d1073c73cba841f13088d6426b93dbb884ce/khmer-1.0.tar.gz#md5=b60639a8b2939836f66495b9a88df757 (from https://pypi.python.org/simple/khmer/), version: 1.0
    Skipping link https://pypi.python.org/packages/69/21/de9ff69a24a90e6f4e788b57a6d911b046cbc768436060c18a0c18c2e187/khmer-2.0-cp34-cp34m-macosx_10_6_intel.whl#md5=ad266bacd15f47b37f26245da34b227f (from https://pypi.python.org/simple/khmer/); it is not c
ompatible with this Python
    Found link https://pypi.python.org/packages/6c/cf/37bd5901fe1322b59cd2cece9c53661944e18dddba3e8ebf2aa2d7834113/khmer-1.3.tar.gz#md5=891aa67d84433792f7926df86af1b4cc (from https://pypi.python.org/simple/khmer/), version: 1.3
    Skipping link https://pypi.python.org/packages/6d/0b/97e3dd8339736c4f4ebf3906274bcf972b2d308bb76db1702c187bfbd9fd/khmer-1.2-cp27-none-macosx_10_10_intel.whl#md5=53b2ec8cf6a68d2f74efc3f6a9e5fb5a (from https://pypi.python.org/simple/khmer/); it is not c
ompatible with this Python
    Skipping link https://pypi.python.org/packages/74/ff/a33663f83fd01cd5ffc9903d8116bd3dfc065f1f865db5c91b080991690b/khmer-0.7-cp27-none-macosx_10_8_intel.whl#md5=56ef85059b18612492d841346b657a5c (from https://pypi.python.org/simple/khmer/); it is not co
mpatible with this Python
    Found link https://pypi.python.org/packages/81/89/085bcb663ac1bd3a0b363b5a1de8f5a1c7d3b10e4a3ec197c976c2911ab9/khmer-0.6.1.tar.gz#md5=68fa5e342eac0eeeba75c8c5f46b94f8 (from https://pypi.python.org/simple/khmer/), version: 0.6.1
    Skipping link https://pypi.python.org/packages/84/a8/09ee794b0db1cc2b113a4f2f56beb325769389c35b48f802289d67297e24/khmer-0.8-cp27-none-macosx_10_9_intel.whl#md5=13b0a73501f884ca66db3c3a762f2acb (from https://pypi.python.org/simple/khmer/); it is not co
mpatible with this Python
    Skipping link https://pypi.python.org/packages/89/b4/310a7e99bac77a488cc482f4184480aa803f65bad8ffacb961c94f819335/khmer-1.4-cp27-none-macosx_10_10_intel.whl#md5=9f5210ef371ed1313ab61b91d473732d (from https://pypi.python.org/simple/khmer/); it is not c
ompatible with this Python
    Found link https://pypi.python.org/packages/92/11/b17b809e155f35cfc17710ea67b7515b6025e141de6506a4af4e32e32b70/khmer-0.7.1.tar.gz#md5=8ae34605918409e87d6962248f6eb7a6 (from https://pypi.python.org/simple/khmer/), version: 0.7.1
    Skipping link https://pypi.python.org/packages/96/b7/76a047a594778ad4d2646754e4454ac9d484b7e64548ebed24362c5aba4f/khmer-1.4.1-cp27-none-macosx_10_6_x86_64.whl#md5=b717fba6a708cc356156143e39ae2ba4 (from https://pypi.python.org/simple/khmer/); it is not
 compatible with this Python
    Skipping link https://pypi.python.org/packages/a5/8e/d814af49f243e9628cc68cf9a89a290fa761a1acdfbf4044e69bb5f3185b/khmer-0.6-py2.7-linux-x86_64.egg#md5=3194ecabe0cd6b50735da8df17cd2b96 (from https://pypi.python.org/simple/khmer/); unsupported archive f
ormat: .egg
    Found link https://pypi.python.org/packages/b8/b5/8143587dd5eba9204dea9eab50b990656b70e03538a44af56eec11a28f02/khmer-1.2.tar.gz#md5=bb47fe790f213d29fd949ec37a2dd473 (from https://pypi.python.org/simple/khmer/), version: 1.2
    Found link https://pypi.python.org/packages/b9/d6/e343a534406110221eb690dc3ffa7548f03f2d51c4d9d407bf2e72278861/khmer-0.6.tar.gz#md5=55ac3f7f531c90e369f727c85a62a049 (from https://pypi.python.org/simple/khmer/), version: 0.6
    Skipping link https://pypi.python.org/packages/d5/8b/ae021e29186d3f9ed8cfdd4f8a81db44f7d4105446dc9e119afd908eea21/khmer-0.7.1-cp27-none-macosx_10_8_intel.whl#md5=131daa6935b35e32be5bfba634566aa5 (from https://pypi.python.org/simple/khmer/); it is not
compatible with this Python
    Found link https://pypi.python.org/packages/df/66/250be153108b73fa745d22b0e141d6d922cd011b6cda2233d46d34bcc596/khmer-1.1.tar.gz#md5=4910da0687e1b9789ff8d99f522f35d0 (from https://pypi.python.org/simple/khmer/), version: 1.1
    Skipping link https://pypi.python.org/packages/f1/61/71c0e5b337f3fb110d22314a90985f58d2a643c8fe701dd832f7a3b3cbe7/khmer-0.6-py2.7-macosx-10.8-intel.egg#md5=0931b13130455ab88c37aa12052a03ba (from https://pypi.python.org/simple/khmer/); unsupported arch
ive format: .egg
    Skipping link https://pypi.python.org/packages/fd/a6/5b64bad521c070581ecb1f22ecfcb33d2b297ec353094438d807028e4be0/khmer-1.0.1-cp27-none-macosx_10_9_x86_64.whl#md5=f8abc8b15cac06bded30ca5483ead63d (from https://pypi.python.org/simple/khmer/); it is not
 compatible with this Python
  Using version 2.0 (newest of versions: 0.6, 0.6.1, 0.7, 0.7.1, 0.8, 1.0, 1.0.1, 1.1, 1.2, 1.3, 1.4, 1.4.1, 2.0)
  Using cached wheel link: file:///home/ubuntu/.cache/pip/wheels/d0/0f/9a/6294ad563949d6693fee4073b3e4b8840f13ddbcad779920c5/khmer-2.0-cp27-cp27m-linux_x86_64.whl
Requirement already satisfied (use --upgrade to upgrade): bz2file in /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages (from khmer)
Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages (from khmer)
Installing collected packages: khmer

Successfully installed khmer-2.0

```

**Comment by ctb** [comment]
Hi Matt, as I feared it is downloading a (binary) wheel rather than building it
from source.  I don't know how to force pip to build from source; if you want
to solve the problem for yourself for now, do your own source install::

```
git clone https://github.com/dib-lab/khmer.git -b v2.0
cd khmer
make install
```

But please leave this issue open and we'll investigate further.

**Comment by macmanes** [comment]
er...

```
pip uninstall khmer
Cannot uninstall requirement khmer, not installed
```
now..

```
git clone https://github.com/dib-lab/khmer.git -b v2.0
cd khmer
make install

...
Adding khmer 2.0 to easy-install.pth file
Installing annotate-partitions.py script to /home/linuxbrew/.linuxbrew/bin
Installing do-partition.py script to /home/linuxbrew/.linuxbrew/bin
Installing filter-abund.py script to /home/linuxbrew/.linuxbrew/bin
Installing find-knots.py script to /home/linuxbrew/.linuxbrew/bin
Installing abundance-dist.py script to /home/linuxbrew/.linuxbrew/bin
Installing filter-stoptags.py script to /home/linuxbrew/.linuxbrew/bin
Installing extract-partitions.py script to /home/linuxbrew/.linuxbrew/bin
Installing abundance-dist-single.py script to /home/linuxbrew/.linuxbrew/bin
Installing unique-kmers.py script to /home/linuxbrew/.linuxbrew/bin
Installing extract-long-sequences.py script to /home/linuxbrew/.linuxbrew/bin
Installing load-graph.py script to /home/linuxbrew/.linuxbrew/bin
Installing split-paired-reads.py script to /home/linuxbrew/.linuxbrew/bin
Installing fastq-to-fasta.py script to /home/linuxbrew/.linuxbrew/bin
Installing merge-partitions.py script to /home/linuxbrew/.linuxbrew/bin
Installing extract-paired-reads.py script to /home/linuxbrew/.linuxbrew/bin
Installing load-into-counting.py script to /home/linuxbrew/.linuxbrew/bin
Installing readstats.py script to /home/linuxbrew/.linuxbrew/bin
Installing sample-reads-randomly.py script to /home/linuxbrew/.linuxbrew/bin
Installing normalize-by-median.py script to /home/linuxbrew/.linuxbrew/bin
Installing partition-graph.py script to /home/linuxbrew/.linuxbrew/bin
Installing trim-low-abund.py script to /home/linuxbrew/.linuxbrew/bin
Installing make-initial-stoptags.py script to /home/linuxbrew/.linuxbrew/bin
Installing filter-abund-single.py script to /home/linuxbrew/.linuxbrew/bin
Installing count-median.py script to /home/linuxbrew/.linuxbrew/bin
Installing interleave-reads.py script to /home/linuxbrew/.linuxbrew/bin

Installed /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages/khmer-2.0-py2.7-linux-x86_64.egg
Processing dependencies for khmer==2.0
Searching for bz2file==0.98
Best match: bz2file 0.98
Adding bz2file 0.98 to easy-install.pth file

Using /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages
Searching for screed==0.9
Best match: screed 0.9
Adding screed 0.9 to easy-install.pth file

Using /home/linuxbrew/.linuxbrew/lib/python2.7/site-packages
Finished processing dependencies for khmer==2.0
```
should be good to go?

```

$ dammit

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/dammit", line 4, in <module>
    import dammit
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/__init__.py", line 12, in <module>
    import tasks
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/tasks.py", line 18, in <module>
    from khmer import HLLCounter, ReadParser
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer-2.0-py2.7-linux-x86_64.egg/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer-2.0-py2.7-linux-x86_64.egg/khmer/_khmer.so)

```

on note - Ubuntu 16.04 does not share this issue. I'm working on 14.04 at ami-c8580bdf

**Comment by ctb** [comment]
rm it, maybe? but I agree with you that it seems like this is our problem
and not the wheel.  We've run into this elsewhere (on mybinder) so we'll
have to look into it.  Thanks for chasing it down - no simple ideas what
to do next, sorry.
