### ISSUE TITLE
check that khmer tests pass as part of screed release/acceptance tests.

### ISSUE THREAD

**Issue by ctb** [dib-lab/khmer#1563]
it would be embarrassing to release a version of screed that broke khmer.

**Comment by standage** [comment]
Ruh roh.

```
===================================================================== FAILURES =====================================================================
_______________________________________________________________ test_read_type_basic _______________________________________________________________

    def test_read_type_basic():
        # test that basic properties of khmer.Read behave like screed.Record
        # Constructing without mandatory arguments should raise an exception
        with pytest.raises(TypeError):
            Read()
    
        name = "895:1:1:1246:14654 1:N:0:NNNNN"
        sequence = "ACGT"
        r = Read(name, sequence)
>       s = Record(dict(name=name, sequence=sequence))

tests/test_read_parsers.py:57:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <[RecursionError("maximum recursion depth exceeded") raised in repr()] Record object at 0x10f0432e8>
name = {'name': '895:1:1:1246:14654 1:N:0:NNNNN', 'sequence': 'ACGT'}, sequence = None, kwargs = {}
d = {'name': {'name': '895:1:1:1246:14654 1:N:0:NNNNN', 'sequence': 'ACGT'}}

    def __init__(self, name=None, sequence=None, **kwargs):
        d = dict()
        if name is not None:
            d['name'] = name
        if sequence is not None:
            d['sequence'] = sequence
    
        d.update(kwargs)
    
        if 'name' not in d:
            raise TypeError("'name' must be specified")
        if 'sequence' not in d:
>           raise TypeError("'sequence' must be specified")
E           TypeError: 'sequence' must be specified

../kenv/lib/python3.5/site-packages/screed/screedRecord.py:35: TypeError
=============================================================== 23 tests deselected ================================================================
============================================== 1 failed, 1054 passed, 23 deselected in 54.52 seconds ===============================================
make: *** [test] Error 1
```

OS 10.12, with latest khmer master and pip install of latest screed master from github.

**Comment by standage** [comment]
Getting 12 of these with v2.0.

```
Traceback (most recent call last):
  File "/Users/standage/Software/khmer/tests/../scripts/trim-low-abund.py", line 381, in <module>
    main()
  File "/Users/standage/Software/khmer/tests/../scripts/trim-low-abund.py", line 274, in main
    new_read = trim_record(read1, trim_at)
  File "/Users/standage/Software/khmer/tests/../scripts/trim-low-abund.py", line 71, in trim_record
    new_read = Record()
  File "/Users/standage/Software/kenv/lib/python3.5/site-packages/screed/screedRecord.py", line 33, in __init__
    raise TypeError("'name' must be specified")
TypeError: 'name' must be specified
```

**Comment by ctb** [comment]
right, because we allowed creation of empty records.  hmm.

**Comment by ctb** [comment]
I guess we have to back out the screedRecord changes for now, then.

**Comment by betatim** [comment]
The empty records bug was fixed in dib-lab/screed#64

Just tried to run `khmer` v2.0 tests with screed@master. This ran a few tests and then used "all the memory", what is the right way of doing this?
```
pip install khmer
py.test --pyargs khmer -m 'not known_failing and not jenkins and not huge'
```

Also just to confirm, we want to make sure that khmer2.0 continues to work with the new release of screed right?

**Comment by ctb** [comment]
On Tue, Jan 31, 2017 at 01:41:30PM -0800, Tim Head wrote:
> Just tried to run `khmer` v2.0 tests with screed@master. This ran a few tests and then used "all the memory", what is the right way of doing this?
> ```
> pip install khmer
> py.test --pyargs khmer -m 'not known_failing and not jenkins and not huge'
> ```

I believe you have to use 'nosetests' with khmer v2.0.

> Also just to confirm, we want to make sure that khmer2.0 continues to work with the new release of screed right?

Yes, because khmer 2.0 didn't define a reliance on a particular version of
screed but rather >= 0.9.

**Comment by betatim** [comment]
D'oh!

The following passes:
```
conda create -n screed-test python=3.5
source activate screed-test
pip install git+https://github.com/dib-lab/screed.git
pip install khmer
python -c "import screed; print(screed.__version__)"
# 0.9+111.g350573e
python -c "import khmer; print(khmer.__version__)"
# 2.0
nosetests khmer --attr '!known_failing,!jenkins,!huge,!linux'
```

**Comment by luizirber** [comment]
khmer 2.0 tests passes with screed 1.0rc1

khmer master doesn't, there is a test where we pass a dict to Record. Not sure if it is an acceptable usage, tho...

PR and discussion: https://github.com/dib-lab/screed/pull/68
(PR works with khmer 2.0 too)

**Comment by standage** [comment]
I'm assuming this can be closed?

**Comment by ctb** [comment]
Yep.
