### ISSUE TITLE
Problem in interleave-reads.py scripts

### ISSUE THREAD

**Issue by thkitapci** [dib-lab/khmer#1568]
Hi,
I installed khmer using 

pip install khmer 

I also did 

pip install khmer --upgrade

Here is the output from installation

-bash-4.2$ pip install khmer
Requirement already satisfied (use --upgrade to upgrade): khmer in /panfs/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages
-bash-4.2$ pip install khmer --upgrade
Collecting khmer
  Downloading khmer-2.0.tar.gz (8.5MB)
    100% |████████████████████████████████| 8.5MB 86kB/s 
Requirement already up-to-date: screed>=0.9 in /panfs/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages (from khmer)
Requirement already up-to-date: bz2file in /panfs/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages (from khmer)
Building wheels for collected packages: khmer
  Running setup.py bdist_wheel for khmer ... done
  Stored in directory: /home/rcf-40/tkitapci/.cache/pip/wheels/d0/0f/9a/6294ad563949d6693fee4073b3e4b8840f13ddbcad779920c5
Successfully built khmer
Installing collected packages: khmer
  Found existing installation: khmer 1.1
    DEPRECATION: Uninstalling a distutils installed project (khmer) has been deprecated and will be removed in a future version. This is due to the fact that uninstalling a distutils project will only partially uninstall the project.
    Uninstalling khmer-1.1:
      Successfully uninstalled khmer-1.1
Successfully installed khmer-2.0

When I try to run the interleave-reads.py scripts I get this error:

-bash-4.2$ interleave-reads.py 
Traceback (most recent call last):
  File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/interleave-reads.py", line 54, in <module>
    from khmer import __version__
  File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/khmer/_khmer.so: undefined symbol: GOMP_parallel

I'll appreciate your help on this

Thanks
T. Hamdi Kitapci

**Comment by ctb** [comment]
Thank you for this report! To me it looks like a mismatch between the libraries that anaconda is using to compile the _khmer extension, and the appropriate library isn't in the path somehow. I've seen this kind of problem before with anaconda but I'm at a loss as to how to further debug it. @betatim @luizirber any thoughts?

**Comment by thkitapci** [comment]
Thanks for the reply. After updating to khmer 2.0 (I was using 1.1 before and I updated while trying to solve the problem with the interleave-reads.py which did not solve the problem)  I realized that now the fastq-to-fasta.py script is not working as well

-bash-4.2$ fastq-to-fasta.py 
Traceback (most recent call last):
  File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/fastq-to-fasta.py", line 49, in <module>
    from khmer import __version__
  File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/khmer/_khmer.so: undefined symbol: GOMP_parallel
 
if I uninstall the khmer 2.0 and install the version 1.1 using 

pip install khmer==1.1

fastq-to-fasta.py script is working fine. 

interleave-reads.py is not working in both 2.0 and 1.1 

I'll appreciate your help for this. Would you suggest me to use the virtualenv and create a brand new environment and install anaconda and khmer from scratch that way ?

Thanks
Hamdi
