### ISSUE TITLE
Install fails on machines without unicode support

### ISSUE THREAD

**Issue by flomock** [dib-lab/khmer#1735]
I tried to install khmer on ubuntu and debian via:
`pip3 install khmer
`
and via:
`pip install git+https://github.com/dib-lab/khmer@master
`
and always get the error:
```
Collecting git+https://github.com/dib-lab/khmer@master
  Cloning https://github.com/dib-lab/khmer (to master) to /tmp/pip-t3br1y4y-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-t3br1y4y-build/setup.py", line 249, in <module>
        authorstr = ', '.join([row[0] for row in authors])
      File "/tmp/pip-t3br1y4y-build/setup.py", line 249, in <listcomp>
        authorstr = ', '.join([row[0] for row in authors])
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 261: ordinal not in range(128)
```
hope you can help.

**Comment by flomock** [comment]
looks for me like you something in your authors.csv file isn't in the ascii format. Maybe a name with strange letters or so.

**Comment by ctb** [comment]
This seems related to https://github.com/dib-lab/khmer/issues/1565.
