### ISSUE TITLE
Having issues with AttributeError: ZipFile(path) as file

### ISSUE THREAD

**Issue by xsharkbaitx** [dib-lab/khmer#1843]
I'm trying to get extract-paired-reads.py to work and am having the following issue:
Traceback (most recent call last):
  File "/usr/bin/extract-paired-reads.py", line 4, in <module>
    import pkg_resources
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 657, in _build_master
    ws = cls()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 650, in __init__
    self.add_entry(entry)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 706, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1966, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1488, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1840, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1717, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1677, in load
    manifest = self.build(path)
  File "/usr/lib/python2.6/site-packages/pkg_resources/__init__.py", line 1650, in build
    with zipfile.ZipFile(path) as zfile:
AttributeError: ZipFile instance has no attribute '__exit__'

We are running python 2.7.6 on our server and the input files are trimmed, qc'd, fasta files.
Thanks in advance.

**Comment by standage** [comment]
Hi, thanks for the report. It looks like it's almost certainly a conflict between different versions of Python on your system. You say Python 2.7.6 is installed, yet all the file paths in the stack trace point to modules in a Python 2.6 installation. Also, if you're using a recent version of khmer installed directly from Github, Python 2.7 is no longer supported and you'll need to upgrade to Python 3 in order to use khmer.

If you have admin privileges on the server, you should be able to follow the following [installation instructions](http://khmer.readthedocs.io/en/latest/user/install.html). If not, I would suggest installing the [Anaconda Python distribution](https://www.anaconda.com/download/) in your server's home directory and installing khmer in a conda virtual environment (instructions included in the link above).

**Comment by standage** [comment]
Did this resolve your issues @xsharkbaitx?
