### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by UltraSpecialException** [dib-lab/khmer#1860]
Tonys-MBP:~ tonynguyen$ cd virtualenv-*; python2.7 virtualenv.py ../khmerEnv; cd ..
New python executable in ../khmerEnv/bin/python
Installing setuptools, pip...done.
Tonys-MBP:~ tonynguyen$ source khmerEnv/bin/activate
(khmerEnv)Tonys-MBP:~ tonynguyen$ pip2 install khmer
Downloading/unpacking khmer
  Downloading khmer-2.1.1.tar.gz (8.5MB): 8.5MB downloaded
  Running setup.py (path:/Users/tonynguyen/khmerEnv/build/khmer/setup.py) egg_info for package khmer
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/Users/tonynguyen/khmerEnv/build/khmer/setup.py", line 304, in <module>
        setup(cmdclass=CMDCLASS, **SETUP_METADATA)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs
        replace_conflicting=True
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match
        return self.obtain(req, installer)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain
        return installer(requirement)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg
        return cmd.easy_install(req)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1013, in run_setup
        run_setup(setup_script, args)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 50, in run_setup
        lambda: execfile(
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 100, in run
        return func()
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 52, in <lambda>
        {'__file__':setup_script, '__name__':'__main__'}
      File "setup.py", line 73, in <module>
        # Checking for OpenMP support. Currently clang doesn't work with OpenMP,
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 264, in __init__
        _Distribution.__init__(self,attrs)
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 298, in finalize_options
        ep.load()(self, ep.name, value)
      File "/private/var/folders/0w/9pfmj2b54hl6cplpkgb2slyw0000gn/T/easy_install-wIdsFC/pytest-runner-2.12.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword
      File "/private/var/folders/0w/9pfmj2b54hl6cplpkgb2slyw0000gn/T/easy_install-wIdsFC/pytest-runner-2.12.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated
    setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)
    Complete output from command python setup.py egg_info:
    /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'python_requires'

  warnings.warn(msg)

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/Users/tonynguyen/khmerEnv/build/khmer/setup.py", line 304, in <module>

    setup(cmdclass=CMDCLASS, **SETUP_METADATA)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 260, in __init__

    self.fetch_build_eggs(attrs.pop('setup_requires'))

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 285, in fetch_build_eggs

    replace_conflicting=True

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve

    dist = best[req.key] = env.best_match(req, ws, installer)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 871, in best_match

    return self.obtain(req, installer)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/pkg_resources.py", line 883, in obtain

    return installer(requirement)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 335, in fetch_build_egg

    return cmd.easy_install(req)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 595, in easy_install

    return self.install_item(spec, dist.location, tmpdir, deps)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 625, in install_item

    dists = self.install_eggs(spec, download, tmpdir)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 822, in install_eggs

    return self.build_and_install(setup_script, setup_base)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1028, in build_and_install

    self.run_setup(setup_script, setup_base, args)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1013, in run_setup

    run_setup(setup_script, args)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 50, in run_setup

    lambda: execfile(

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 100, in run

    return func()

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/sandbox.py", line 52, in <lambda>

    {'__file__':setup_script, '__name__':'__main__'}

  File "setup.py", line 73, in <module>

    # Checking for OpenMP support. Currently clang doesn't work with OpenMP,

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 264, in __init__

    _Distribution.__init__(self,attrs)

  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/Users/tonynguyen/khmerEnv/lib/python2.7/site-packages/setuptools/dist.py", line 298, in finalize_options

    ep.load()(self, ep.name, value)

  File "/private/var/folders/0w/9pfmj2b54hl6cplpkgb2slyw0000gn/T/easy_install-wIdsFC/pytest-runner-2.12.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/integration.py", line 10, in version_keyword

  File "/private/var/folders/0w/9pfmj2b54hl6cplpkgb2slyw0000gn/T/easy_install-wIdsFC/pytest-runner-2.12.2/setuptools_scm-2.0.0-py2.7.egg/setuptools_scm/version.py", line 44, in _warn_if_setuptools_outdated

setuptools_scm.version.SetuptoolsOutdatedWarning: your setuptools is too old (<12)

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /Users/tonynguyen/khmerEnv/build/khmer
Storing debug log for failure in /Users/tonynguyen/.pip/pip.log
(khmerEnv)Tonys-MBP:~ tonynguyen$ 

I tried to install khmer but I keep getting this egg_info error. Any help?

**Comment by standage** [comment]
Hi @UltraSpecialException!

It looks like you're installing khmer in a python 2 environment. We recently stopped supporting Python 2, so khmer requires Python 3.4 or higher. Sorry the default installation instructions don't reflect this yet. Please try [the latest version of the installation instructions](khmer.readthedocs.io/en/latest/user/install.html) and let us know if this solves your issue. Thanks!

**Comment by andrea-w** [comment]
Hi @standage 

I'm encountering the same installation issue as the OP, but when I click your link to the latest installation instructions, I get a 404 error. Could you please check the link? Thanks!

**Comment by luizirber** [comment]
@standage I fixed the link in your comment, it works now

**Comment by luizirber** [comment]
@UltraSpecialException this error happens because you have a (very) old version of setuptools. Try to do `pip2 install -U setuptools` before running `pip2 install khmer`

(in this case you're still installing khmer 2.1.1, which does support Python 2. If you install from master, you need the new instructions that @standage posted)
