### ISSUE TITLE
No local packages or download links found for pytest-runner

### ISSUE THREAD

**Issue by LujingF** [dib-lab/khmer#1879]
Hi,
When I use the command 'pip install khmer', I got the error message:
Collecting khmer
  Using cached https://files.pythonhosted.org/packages/40/5a/328d310361d98bb2f29361128eaa2493f44b51997d6837c72f1766c4ec7b/khmer-2.1.1-cp27-cp27mu-manylinux1_x86_64.whl
Collecting bz2file (from khmer)
  Using cached https://files.pythonhosted.org/packages/61/39/122222b5e85cd41c391b68a99ee296584b2a2d1d233e7ee32b4532384f2d/bz2file-0.98.tar.gz
Collecting screed>=1.0 (from khmer)
  Using cached https://files.pythonhosted.org/packages/e7/7a/b5f16a9861ac497b346b2f5205e8dc35103eeba1e6fdffa114c47e0b35ba/screed-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    /HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/command/install_scripts.py:3: UserWarning: Module backports was already imported from None, but /HOME/packages/anaconda2/lib/python2.7/site-packages is being added to sys.path
      from pkg_resources import Distribution, PathMetadata, ensure_directory
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    No local packages or download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-6sUB3F/screed/setup.py", line 34, in <module>
        'screed = screed.__main__:main'
      File "/HOME/packages/anaconda2/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/dist.py", line 221, in __init__
        self.fetch_build_eggs(attrs.pop('setup_requires'))
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/dist.py", line 245, in fetch_build_eggs
        parse_requirements(requires), installer=self.fetch_build_egg
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 538, in resolve
        dist = best[req.key] = env.best_match(req, self, installer)
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 780, in best_match
        return self.obtain(req, installer) # try and download/install
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 792, in obtain
        return installer(requirement)
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/dist.py", line 293, in fetch_build_egg
        return cmd.easy_install(req)
      File "/HOME/.local/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/setuptools/command/easy_install.py", line 465, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

I have already installed pytest-runner-4.2, but it seems this package couldn't find it.
I downloaded source code from github and tried to install it according to "python setup.py install", but  I got a error ：
 File "setup.py", line 74
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

what should I do? thanks

**Comment by standage** [comment]
Hi @LujingF!

I've had problems with pytest-runner as well, and I think the version currently hard-coded in the `setup.py` file is problematic. I would like to submit a fix for this soon.

But I think your problem might be even simpler than that. It appears that you're trying to install khmer in a Python 2.7 environment. khmer no longer supports Python version 2: you'll need to make sure Python 3 is installed and that you're installing khmer to your Python 3 distribution (for example, with `pip3` or with a virtual environment). The latest version of [our installation docs](https://khmer.readthedocs.io/en/latest/user/install.html) cover this in detail.

Please let us know if you continue to run into problems.
