### ISSUE TITLE
Installation fails with Python 3.12

### ISSUE THREAD

**Issue by mikemc** [dib-lab/khmer#1927]
The error appears to be the same as discussed at https://github.com/pydata/pandas-datareader/issues/969. When I try installing with Python 3.12, I get

```
~ ❯ python3 -m venv khmerEnv
source khmerEnv/bin/activate
(khmerEnv) ~ ❯ pip install khmer

Collecting khmer
  Using cached khmer-2.1.1.tar.gz (8.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [31 lines of output]
      /private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-install-e6nvyrxg/khmer_b293069cabde477f8035f0594cb322fb/versioneer.py:421: SyntaxWarning: invalid escape sequence '\s'
        LONG_VERSION_PY['git'] = '''
      Traceback (most recent call last):
        File "/Users/michael/khmerEnv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/michael/khmerEnv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Users/michael/khmerEnv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-build-env-j3akbz40/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-build-env-j3akbz40/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-build-env-j3akbz40/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-build-env-j3akbz40/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 168, in <module>
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-install-e6nvyrxg/khmer_b293069cabde477f8035f0594cb322fb/versioneer.py", line 1480, in get_version
          return get_versions()["version"]
                 ^^^^^^^^^^^^^^
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-install-e6nvyrxg/khmer_b293069cabde477f8035f0594cb322fb/versioneer.py", line 1412, in get_versions
          cfg = get_config_from_root(root)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/f5/fqbhr9ps7dn058v21yczz_0r0000gn/T/pip-install-e6nvyrxg/khmer_b293069cabde477f8035f0594cb322fb/versioneer.py", line 342, in get_config_from_root
          parser = configparser.SafeConfigParser()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

but I can install with Python 3.11.9 without error

**Comment by lskatz** [comment]
Can we update the conda recipe to python < 3.12 then?

**Comment by dr-joe-wirth** [comment]
I noticed this as well. I believe that `SafeConfigParser` was depricated and/or replaced with `ConfigParser` in 3.12. This is likely the source of the incompatibility.

**Comment by ctb** [comment]
hi folks,

note also this PR: https://github.com/dib-lab/khmer/pull/1922

discussion on maintenance moving forward here: https://github.com/dib-lab/khmer/issues/1928
